<?
$aMenuLinks = Array(
	Array(
		"Студии",
		"/moskva/novostroyki/?search=[]&rooms=5",
		Array(), 
		Array(),
		"" 
	),
    Array(
        "Однокомнатные",
        "/moskva/novostroyki/?search=[]&rooms=6",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Двухкомнатные",
        "/moskva/novostroyki/?search=[]&rooms=7",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Трехкомнатные",
        "/moskva/novostroyki/?search=[]&rooms=8",
        Array(),
        Array(),
        ""
    ),
	Array(
		"Четырехкомнатные",
		"/moskva/novostroyki/?search=[]&rooms=9",
		Array(), 
		Array(),
		"" 
	),
);
?>