<?
$aMenuLinks = Array(
    Array(
        "Новостройки",
		"/moskva/novostroyki/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Вторичная",
		"/moskva/kupit-kvartiru/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Загородная",
        "/moskva/kupit-dom/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Зарубежная",
        "/moskva/nedvizhimost-za-rubezhom/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "О нас",
        "/moskva/about/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "/moskva/contacts/",
        Array(),
        Array(),
        ""
    )
);
?>