<?
$aMenuLinks = Array(
    Array(
        "Адмиралтейский",
        '/spb/novostroyki/?search=[{"id":"area_1113","title":"Адмиралтейский%20р-н","exclude":false}]',
        Array(),
        Array(),
        ""
    ),
    Array(
        "Петроградский",
        '/spb/novostroyki/?search=[{"id":"area_1125","title":"Петроградский%20р-н","exclude":false}]',
        Array(),
        Array(),
        ""
    ),
    Array(
        "Московский",
        '/spb/novostroyki/?search=[{"id":"area_1123","title":"Московский%20р-н","exclude":false}]',
        Array(),
        Array(),
        ""
    ),
	Array(
		"Приморский",
		'/spb/novostroyki/?search=[{"id":"area_1127","title":"Приморский%20р-н","exclude":false}]',
		Array(), 
		Array(),
		"" 
	),
    Array(
        "Фрунзенский",
        '/spb/novostroyki/?search=[{"id":"area_1129","title":"Фрунзенский%20р-н","exclude":false}]',
        Array(),
        Array(),
        ""
    ),
    Array(
        "Красногвардейский",
        '/spb/novostroyki/?search=[{"id":"area_1119","title":"Красногвардейский%20р-н","exclude":false}]',
        Array(),
        Array(),
        ""
    ),
    Array(
        "Красносельский",
        '/spb/novostroyki/?search=[{"id":"area_1120","title":"Красносельский%20р-н","exclude":false}]',
        Array(),
        Array(),
        ""
    ),
    Array(
        "Василеостровский",
        '/spb/novostroyki/?search=[{"id":"area_1114","title":"Василеостровский%20р-н","exclude":false}]',
        Array(),
        Array(),
        ""
    ),
    Array(
        "Выборгский",
        '/spb/novostroyki/?search=[{"id":"area_1115","title":"Выборгский%20р-н","exclude":false}]',
        Array(),
        Array(),
        ""
    ),
);
?>